/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO14827-2"
 * 	found in "../asn1c/J2735_201603DA+ITSK4-0.4_fix.update"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -pdu=MessageFrame`
 */

#ifndef	_AlternateRequest_H_
#define	_AlternateRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SubscriptionType.h"

#ifdef __cplusplus
extern "C" {
#endif

/* AlternateRequest */
typedef SubscriptionType_t	 AlternateRequest_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_AlternateRequest_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_AlternateRequest;
asn_struct_free_f AlternateRequest_free;
asn_struct_print_f AlternateRequest_print;
asn_constr_check_f AlternateRequest_constraint;
ber_type_decoder_f AlternateRequest_decode_ber;
der_type_encoder_f AlternateRequest_encode_der;
xer_type_decoder_f AlternateRequest_decode_xer;
xer_type_encoder_f AlternateRequest_encode_xer;
oer_type_decoder_f AlternateRequest_decode_oer;
oer_type_encoder_f AlternateRequest_encode_oer;
per_type_decoder_f AlternateRequest_decode_uper;
per_type_encoder_f AlternateRequest_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _AlternateRequest_H_ */
#include <asn_internal.h>
