/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO14827-2"
 * 	found in "../asn1c/J2735_201603DA+ITSK4-0.4_fix.update"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -pdu=MessageFrame`
 */

#include "C2CAuthenticatedMessage.h"

static int
datex_DataPacket_number_3_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

/*
 * This type is implemented using NativeInteger,
 * so here we adjust the DEF accordingly.
 */
static int
memb_datex_AuthenticationInfo_text_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_datex_DataPacket_number_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

static int
memb_datex_DataPacketPriority_number_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 10)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_type_datex_DataPacket_number_constr_3 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_type_datex_DataPacket_number_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_datex_AuthenticationInfo_text_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..255)) */};
static asn_per_constraints_t asn_PER_memb_datex_AuthenticationInfo_text_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (SIZE(0..255)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_datex_DataPacket_number_constr_3 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_memb_datex_DataPacket_number_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_datex_DataPacketPriority_number_constr_4 CC_NOTUSED = {
	{ 1, 1 }	/* (0..10) */,
	-1};
static asn_per_constraints_t asn_PER_memb_datex_DataPacketPriority_number_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  10 }	/* (0..10) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_specifics_t asn_SPC_datex_DataPacket_number_specs_3 = {
	0,	0,	0,	0,	0,
	0,	/* Native long size */
	1	/* Unsigned representation */
};
static const ber_tlv_tag_t asn_DEF_datex_DataPacket_number_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_datex_DataPacket_number_3 = {
	"datex-DataPacket-number",
	"datex-DataPacket-number",
	&asn_OP_NativeInteger,
	asn_DEF_datex_DataPacket_number_tags_3,
	sizeof(asn_DEF_datex_DataPacket_number_tags_3)
		/sizeof(asn_DEF_datex_DataPacket_number_tags_3[0]) - 1, /* 1 */
	asn_DEF_datex_DataPacket_number_tags_3,	/* Same as above */
	sizeof(asn_DEF_datex_DataPacket_number_tags_3)
		/sizeof(asn_DEF_datex_DataPacket_number_tags_3[0]), /* 2 */
	{ &asn_OER_type_datex_DataPacket_number_constr_3, &asn_PER_type_datex_DataPacket_number_constr_3, datex_DataPacket_number_3_constraint },
	0, 0,	/* No members */
	&asn_SPC_datex_DataPacket_number_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_C2CAuthenticatedMessage_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct C2CAuthenticatedMessage, datex_AuthenticationInfo_text),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ &asn_OER_memb_datex_AuthenticationInfo_text_constr_2, &asn_PER_memb_datex_AuthenticationInfo_text_constr_2,  memb_datex_AuthenticationInfo_text_constraint_1 },
		0, 0, /* No default value */
		"datex-AuthenticationInfo-text"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct C2CAuthenticatedMessage, datex_DataPacket_number),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_datex_DataPacket_number_3,
		0,
		{ &asn_OER_memb_datex_DataPacket_number_constr_3, &asn_PER_memb_datex_DataPacket_number_constr_3,  memb_datex_DataPacket_number_constraint_1 },
		0, 0, /* No default value */
		"datex-DataPacket-number"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct C2CAuthenticatedMessage, datex_DataPacketPriority_number),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_datex_DataPacketPriority_number_constr_4, &asn_PER_memb_datex_DataPacketPriority_number_constr_4,  memb_datex_DataPacketPriority_number_constraint_1 },
		0, 0, /* No default value */
		"datex-DataPacketPriority-number"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct C2CAuthenticatedMessage, options),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HeaderOptions,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"options"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct C2CAuthenticatedMessage, pdu),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_PDUs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pdu"
		},
};
static const ber_tlv_tag_t asn_DEF_C2CAuthenticatedMessage_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_C2CAuthenticatedMessage_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* datex-AuthenticationInfo-text */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* datex-DataPacket-number */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* datex-DataPacketPriority-number */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* options */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* pdu */
};
static asn_SEQUENCE_specifics_t asn_SPC_C2CAuthenticatedMessage_specs_1 = {
	sizeof(struct C2CAuthenticatedMessage),
	offsetof(struct C2CAuthenticatedMessage, _asn_ctx),
	asn_MAP_C2CAuthenticatedMessage_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_C2CAuthenticatedMessage = {
	"C2CAuthenticatedMessage",
	"C2CAuthenticatedMessage",
	&asn_OP_SEQUENCE,
	asn_DEF_C2CAuthenticatedMessage_tags_1,
	sizeof(asn_DEF_C2CAuthenticatedMessage_tags_1)
		/sizeof(asn_DEF_C2CAuthenticatedMessage_tags_1[0]), /* 1 */
	asn_DEF_C2CAuthenticatedMessage_tags_1,	/* Same as above */
	sizeof(asn_DEF_C2CAuthenticatedMessage_tags_1)
		/sizeof(asn_DEF_C2CAuthenticatedMessage_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_C2CAuthenticatedMessage_1,
	5,	/* Elements count */
	&asn_SPC_C2CAuthenticatedMessage_specs_1	/* Additional specs */
};

