/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AddGrpD"
 * 	found in "../asn1c/J2735_201603DA+ITSK4-0.4_fix.update"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -pdu=MessageFrame`
 */

#ifndef	_CITSPVD_H_
#define	_CITSPVD_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TransitStatus.h"
#include "Acceleration.h"
#include "LaneID.h"
#include <NativeInteger.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CITSLog;

/* CITSPVD */
typedef struct CITSPVD {
	TransitStatus_t	*transitStatus	/* OPTIONAL */;
	Acceleration_t	*acceleration	/* OPTIONAL */;
	struct CITSPVD__worklanes {
		A_SEQUENCE_OF(LaneID_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *worklanes;
	LaneID_t	*curlane	/* OPTIONAL */;
	long	*vehiclecnt	/* OPTIONAL */;
	struct CITSLog	*servicelog	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CITSPVD_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CITSPVD;
extern asn_SEQUENCE_specifics_t asn_SPC_CITSPVD_specs_1;
extern asn_TYPE_member_t asn_MBR_CITSPVD_1[6];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CITSLog.h"

#endif	/* _CITSPVD_H_ */
#include <asn_internal.h>
