/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AddGrpD"
 * 	found in "../asn1c/J2735_201603DA+ITSK4-0.4_fix.update"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -pdu=MessageFrame`
 */

#ifndef	_CITSLog_H_
#define	_CITSLog_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "DDateTime.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CITSLog */
typedef struct CITSLog {
	long	 id;
	unsigned long	 msgid;
	long	 posid;
	unsigned long	 event;
	long	 display;
	long	 hmistate;
	DDateTime_t	 time;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CITSLog_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_msgid_3;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_event_5;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_CITSLog;
extern asn_SEQUENCE_specifics_t asn_SPC_CITSLog_specs_1;
extern asn_TYPE_member_t asn_MBR_CITSLog_1[7];

#ifdef __cplusplus
}
#endif

#endif	/* _CITSLog_H_ */
#include <asn_internal.h>
