/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AddGrpD"
 * 	found in "../asn1c/J2735_201603DA+ITSK4-0.4_fix.update"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -pdu=MessageFrame`
 */

#include "CITSRSA.h"

static int
memb_temprature_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= -32767 && value <= 32767)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_humidity_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= -32767 && value <= 32767)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_percent_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 100)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_limitspeed_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 65534)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_lanewidth_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 65534)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_laneset_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 4)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_type_laneset_constr_7 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..4)) */};
static asn_per_constraints_t asn_PER_type_laneset_constr_7 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 2,  2,  1,  4 }	/* (SIZE(1..4)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_temprature_constr_2 CC_NOTUSED = {
	{ 2, 0 }	/* (-32767..32767) */,
	-1};
static asn_per_constraints_t asn_PER_memb_temprature_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 16,  16, -32767,  32767 }	/* (-32767..32767) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_humidity_constr_3 CC_NOTUSED = {
	{ 2, 0 }	/* (-32767..32767) */,
	-1};
static asn_per_constraints_t asn_PER_memb_humidity_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 16,  16, -32767,  32767 }	/* (-32767..32767) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_percent_constr_4 CC_NOTUSED = {
	{ 1, 1 }	/* (0..100) */,
	-1};
static asn_per_constraints_t asn_PER_memb_percent_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 7,  7,  0,  100 }	/* (0..100) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_limitspeed_constr_5 CC_NOTUSED = {
	{ 2, 1 }	/* (0..65534) */,
	-1};
static asn_per_constraints_t asn_PER_memb_limitspeed_constr_5 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 16,  16,  0,  65534 }	/* (0..65534) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_lanewidth_constr_6 CC_NOTUSED = {
	{ 2, 1 }	/* (0..65534) */,
	-1};
static asn_per_constraints_t asn_PER_memb_lanewidth_constr_6 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 16,  16,  0,  65534 }	/* (0..65534) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_laneset_constr_7 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..4)) */};
static asn_per_constraints_t asn_PER_memb_laneset_constr_7 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 2,  2,  1,  4 }	/* (SIZE(1..4)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_laneset_7[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_LaneID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_laneset_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_laneset_specs_7 = {
	sizeof(struct CITSRSA__laneset),
	offsetof(struct CITSRSA__laneset, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_laneset_7 = {
	"laneset",
	"laneset",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_laneset_tags_7,
	sizeof(asn_DEF_laneset_tags_7)
		/sizeof(asn_DEF_laneset_tags_7[0]) - 1, /* 1 */
	asn_DEF_laneset_tags_7,	/* Same as above */
	sizeof(asn_DEF_laneset_tags_7)
		/sizeof(asn_DEF_laneset_tags_7[0]), /* 2 */
	{ &asn_OER_type_laneset_constr_7, &asn_PER_type_laneset_constr_7, SEQUENCE_OF_constraint },
	asn_MBR_laneset_7,
	1,	/* Single element */
	&asn_SPC_laneset_specs_7	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_CITSRSA_1[] = {
	{ ATF_POINTER, 6, offsetof(struct CITSRSA, temprature),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_temprature_constr_2, &asn_PER_memb_temprature_constr_2,  memb_temprature_constraint_1 },
		0, 0, /* No default value */
		"temprature"
		},
	{ ATF_POINTER, 5, offsetof(struct CITSRSA, humidity),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_humidity_constr_3, &asn_PER_memb_humidity_constr_3,  memb_humidity_constraint_1 },
		0, 0, /* No default value */
		"humidity"
		},
	{ ATF_POINTER, 4, offsetof(struct CITSRSA, percent),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_percent_constr_4, &asn_PER_memb_percent_constr_4,  memb_percent_constraint_1 },
		0, 0, /* No default value */
		"percent"
		},
	{ ATF_POINTER, 3, offsetof(struct CITSRSA, limitspeed),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_limitspeed_constr_5, &asn_PER_memb_limitspeed_constr_5,  memb_limitspeed_constraint_1 },
		0, 0, /* No default value */
		"limitspeed"
		},
	{ ATF_POINTER, 2, offsetof(struct CITSRSA, lanewidth),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_lanewidth_constr_6, &asn_PER_memb_lanewidth_constr_6,  memb_lanewidth_constraint_1 },
		0, 0, /* No default value */
		"lanewidth"
		},
	{ ATF_POINTER, 1, offsetof(struct CITSRSA, laneset),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		0,
		&asn_DEF_laneset_7,
		0,
		{ &asn_OER_memb_laneset_constr_7, &asn_PER_memb_laneset_constr_7,  memb_laneset_constraint_1 },
		0, 0, /* No default value */
		"laneset"
		},
};
static const int asn_MAP_CITSRSA_oms_1[] = { 0, 1, 2, 3, 4, 5 };
static const ber_tlv_tag_t asn_DEF_CITSRSA_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_CITSRSA_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* temprature */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* humidity */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* percent */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* limitspeed */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* lanewidth */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* laneset */
};
asn_SEQUENCE_specifics_t asn_SPC_CITSRSA_specs_1 = {
	sizeof(struct CITSRSA),
	offsetof(struct CITSRSA, _asn_ctx),
	asn_MAP_CITSRSA_tag2el_1,
	6,	/* Count of tags in the map */
	asn_MAP_CITSRSA_oms_1,	/* Optional members */
	6, 0,	/* Root/Additions */
	6,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_CITSRSA = {
	"CITSRSA",
	"CITSRSA",
	&asn_OP_SEQUENCE,
	asn_DEF_CITSRSA_tags_1,
	sizeof(asn_DEF_CITSRSA_tags_1)
		/sizeof(asn_DEF_CITSRSA_tags_1[0]), /* 1 */
	asn_DEF_CITSRSA_tags_1,	/* Same as above */
	sizeof(asn_DEF_CITSRSA_tags_1)
		/sizeof(asn_DEF_CITSRSA_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_CITSRSA_1,
	6,	/* Elements count */
	&asn_SPC_CITSRSA_specs_1	/* Additional specs */
};

