/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AddGrpD"
 * 	found in "../asn1c/J2735_201603DA+ITSK4-0.4_fix.update"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -pdu=MessageFrame`
 */

#ifndef	_CITSRSA_H_
#define	_CITSRSA_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "LaneID.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CITSRSA */
typedef struct CITSRSA {
	long	*temprature	/* OPTIONAL */;
	long	*humidity	/* OPTIONAL */;
	long	*percent	/* OPTIONAL */;
	long	*limitspeed	/* OPTIONAL */;
	long	*lanewidth	/* OPTIONAL */;
	struct CITSRSA__laneset {
		A_SEQUENCE_OF(LaneID_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *laneset;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CITSRSA_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CITSRSA;
extern asn_SEQUENCE_specifics_t asn_SPC_CITSRSA_specs_1;
extern asn_TYPE_member_t asn_MBR_CITSRSA_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _CITSRSA_H_ */
#include <asn_internal.h>
