/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO14827-2"
 * 	found in "../asn1c/J2735_201603DA+ITSK4-0.4_fix.update"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -pdu=MessageFrame`
 */

#ifndef	_DatexDataPacket_H_
#define	_DatexDataPacket_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DatexDataPacket__datex_Version_number {
	DatexDataPacket__datex_Version_number_experimental	= 0,
	DatexDataPacket__datex_Version_number_version1	= 1
	/*
	 * Enumeration is extensible
	 */
} e_DatexDataPacket__datex_Version_number;

/* DatexDataPacket */
typedef struct DatexDataPacket {
	long	 datex_Version_number;
	OCTET_STRING_t	 datex_Data;
	OCTET_STRING_t	 datex_Crc_nbr;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DatexDataPacket_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_datex_Version_number_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_DatexDataPacket;

#ifdef __cplusplus
}
#endif

#endif	/* _DatexDataPacket_H_ */
#include <asn_internal.h>
