/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO14827-2"
 * 	found in "../asn1c/J2735_201603DA+ITSK4-0.4_fix.update"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -pdu=MessageFrame`
 */

#ifndef	_HeaderOptions_H_
#define	_HeaderOptions_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTF8String.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Cost;
struct Time;

/* HeaderOptions */
typedef struct HeaderOptions {
	UTF8String_t	*datex_Origin_text	/* OPTIONAL */;
	OCTET_STRING_t	*datex_OriginAddress_location	/* OPTIONAL */;
	UTF8String_t	*datex_Sender_text	/* OPTIONAL */;
	OCTET_STRING_t	*datex_SenderAddress_location	/* OPTIONAL */;
	UTF8String_t	*datex_Destination_text	/* OPTIONAL */;
	OCTET_STRING_t	*datex_DestinationAddress_location	/* OPTIONAL */;
	struct Cost	*datex_Cost	/* OPTIONAL */;
	struct Time	*datex_DataPacket_time	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HeaderOptions_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HeaderOptions;
extern asn_SEQUENCE_specifics_t asn_SPC_HeaderOptions_specs_1;
extern asn_TYPE_member_t asn_MBR_HeaderOptions_1[8];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Cost.h"
#include "Time.h"

#endif	/* _HeaderOptions_H_ */
#include <asn_internal.h>
