/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO14827-2"
 * 	found in "../asn1c/J2735_201603DA+ITSK4-0.4_fix.update"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -pdu=MessageFrame`
 */

#ifndef	_Initiate_H_
#define	_Initiate_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTF8String.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Initiate */
typedef struct Initiate {
	UTF8String_t	 datex_Sender_txt;
	UTF8String_t	 datex_Destination_txt;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Initiate_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Initiate;
extern asn_SEQUENCE_specifics_t asn_SPC_Initiate_specs_1;
extern asn_TYPE_member_t asn_MBR_Initiate_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _Initiate_H_ */
#include <asn_internal.h>
