/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO14827-2"
 * 	found in "../asn1c/J2735_201603DA+ITSK4-0.4_fix.update"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -pdu=MessageFrame`
 */

#ifndef	_Login_H_
#define	_Login_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTF8String.h>
#include <OCTET_STRING.h>
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <OBJECT_IDENTIFIER.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Login__datexLogin_Initiator_cd {
	Login__datexLogin_Initiator_cd_serverInitiated	= 0,
	Login__datexLogin_Initiator_cd_clientInitiated	= 1
	/*
	 * Enumeration is extensible
	 */
} e_Login__datexLogin_Initiator_cd;

/* Login */
typedef struct Login {
	UTF8String_t	 datex_Sender_txt;
	UTF8String_t	 datex_Destination_txt;
	OCTET_STRING_t	 datexLogin_UserName_txt;
	OCTET_STRING_t	 datexLogin_Password_txt;
	struct Login__datexLogin_EncodingRules_id {
		A_SEQUENCE_OF(OBJECT_IDENTIFIER_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} datexLogin_EncodingRules_id;
	long	 datexLogin_HeartbeatDurationMax_qty;
	long	 datexLogin_ResponseTimeOut_qty;
	long	 datexLogin_Initiator_cd;
	long	 datexLogin_DatagramSize_qty;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Login_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_datexLogin_Initiator_cd_10;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_Login;
extern asn_SEQUENCE_specifics_t asn_SPC_Login_specs_1;
extern asn_TYPE_member_t asn_MBR_Login_1[9];

#ifdef __cplusplus
}
#endif

#endif	/* _Login_H_ */
#include <asn_internal.h>
