/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO14827-2"
 * 	found in "../asn1c/J2735_201603DA+ITSK4-0.4_fix.update"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -pdu=MessageFrame`
 */

#ifndef	_Logout_H_
#define	_Logout_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Logout {
	Logout_other	= 0,
	Logout_serverRequested	= 1,
	Logout_clientRequested	= 2,
	Logout_serverShutdown	= 3,
	Logout_clientShutdown	= 4,
	Logout_serverCommProblems	= 5,
	Logout_clientCommProblems	= 6
	/*
	 * Enumeration is extensible
	 */
} e_Logout;

/* Logout */
typedef long	 Logout_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Logout_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Logout;
extern const asn_INTEGER_specifics_t asn_SPC_Logout_specs_1;
asn_struct_free_f Logout_free;
asn_struct_print_f Logout_print;
asn_constr_check_f Logout_constraint;
ber_type_decoder_f Logout_decode_ber;
der_type_encoder_f Logout_encode_der;
xer_type_decoder_f Logout_decode_xer;
xer_type_encoder_f Logout_encode_xer;
oer_type_decoder_f Logout_decode_oer;
oer_type_encoder_f Logout_encode_oer;
per_type_decoder_f Logout_decode_uper;
per_type_encoder_f Logout_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Logout_H_ */
#include <asn_internal.h>
