/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../asn1c/J2735_201603DA+ITSK4-0.4_fix.update"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -pdu=MessageFrame`
 */

#ifndef	_PartIIcontent_H_
#define	_PartIIcontent_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PartII-Id.h"
#include <ANY.h>
#include <asn_ioc.h>
#include "VehicleSafetyExtensions.h"
#include "SpecialVehicleExtensions.h"
#include "SupplementalVehicleExtensions.h"
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PartIIcontent__partII_Value_PR {
	PartIIcontent__partII_Value_PR_NOTHING,	/* No components present */
	PartIIcontent__partII_Value_PR_VehicleSafetyExtensions,
	PartIIcontent__partII_Value_PR_SpecialVehicleExtensions,
	PartIIcontent__partII_Value_PR_SupplementalVehicleExtensions
} PartIIcontent__partII_Value_PR;

/* PartIIcontent */
typedef struct PartIIcontent {
	PartII_Id_t	 partII_Id;
	struct PartIIcontent__partII_Value {
		PartIIcontent__partII_Value_PR present;
		union {
			VehicleSafetyExtensions_t	 VehicleSafetyExtensions;
			SpecialVehicleExtensions_t	 SpecialVehicleExtensions;
			SupplementalVehicleExtensions_t	 SupplementalVehicleExtensions;
		};
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} partII_Value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PartIIcontent_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PartIIcontent;
extern asn_SEQUENCE_specifics_t asn_SPC_PartIIcontent_specs_1;
extern asn_TYPE_member_t asn_MBR_PartIIcontent_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _PartIIcontent_H_ */
#include <asn_internal.h>
