/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO14827-2"
 * 	found in "../asn1c/J2735_201603DA+ITSK4-0.4_fix.update"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -pdu=MessageFrame`
 */

#include "PDUs.h"

static asn_oer_constraints_t asn_OER_type_PDUs_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_PDUs_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  9 }	/* (0..9) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_PDUs_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PDUs, datex_Initiate_null),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Initiate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"datex-Initiate-null"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDUs, login),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Login,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"login"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDUs, fred),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FrED,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"fred"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDUs, terminate),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Terminate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"terminate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDUs, logout),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Logout,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"logout"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDUs, subscription),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Subscription,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"subscription"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDUs, publication),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Publication,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"publication"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDUs, transfer_done),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TransferDone,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"transfer-done"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDUs, accept),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Accept,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"accept"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDUs, reject),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Reject,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"reject"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_PDUs_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* datex-Initiate-null */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* login */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* fred */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* terminate */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* logout */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* subscription */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* publication */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* transfer-done */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* accept */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 } /* reject */
};
asn_CHOICE_specifics_t asn_SPC_PDUs_specs_1 = {
	sizeof(struct PDUs),
	offsetof(struct PDUs, _asn_ctx),
	offsetof(struct PDUs, present),
	sizeof(((struct PDUs *)0)->present),
	asn_MAP_PDUs_tag2el_1,
	10,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_PDUs = {
	"PDUs",
	"PDUs",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_PDUs_constr_1, &asn_PER_type_PDUs_constr_1, CHOICE_constraint },
	asn_MBR_PDUs_1,
	10,	/* Elements count */
	&asn_SPC_PDUs_specs_1	/* Additional specs */
};

