/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO14827-2"
 * 	found in "../asn1c/J2735_201603DA+ITSK4-0.4_fix.update"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -pdu=MessageFrame`
 */

#include "Publish-Format.h"

static int
memb_datexPublish_FileName_txt_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const UTF8String_t *st = (const UTF8String_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = UTF8String_length(st);
	if((ssize_t)size < 0) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: UTF-8: broken encoding (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if((size <= 2000)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_datexPublish_FileName_txt_constr_4 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_memb_datexPublish_FileName_txt_constr_4 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_Publish_Format_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_Publish_Format_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_datexPublish_Data_2[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_PublicationData,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_datexPublish_Data_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_datexPublish_Data_specs_2 = {
	sizeof(struct Publish_Format__datexPublish_Data),
	offsetof(struct Publish_Format__datexPublish_Data, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_datexPublish_Data_2 = {
	"datexPublish-Data",
	"datexPublish-Data",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_datexPublish_Data_tags_2,
	sizeof(asn_DEF_datexPublish_Data_tags_2)
		/sizeof(asn_DEF_datexPublish_Data_tags_2[0]) - 1, /* 1 */
	asn_DEF_datexPublish_Data_tags_2,	/* Same as above */
	sizeof(asn_DEF_datexPublish_Data_tags_2)
		/sizeof(asn_DEF_datexPublish_Data_tags_2[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_datexPublish_Data_2,
	1,	/* Single element */
	&asn_SPC_datexPublish_Data_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_Publish_Format_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Publish_Format, datexPublish_Data),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_datexPublish_Data_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"datexPublish-Data"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Publish_Format, datexPublish_FileName_txt),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ &asn_OER_memb_datexPublish_FileName_txt_constr_4, &asn_PER_memb_datexPublish_FileName_txt_constr_4,  memb_datexPublish_FileName_txt_constraint_1 },
		0, 0, /* No default value */
		"datexPublish-FileName-txt"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_Publish_Format_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* datexPublish-Data */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* datexPublish-FileName-txt */
};
asn_CHOICE_specifics_t asn_SPC_Publish_Format_specs_1 = {
	sizeof(struct Publish_Format),
	offsetof(struct Publish_Format, _asn_ctx),
	offsetof(struct Publish_Format, present),
	sizeof(((struct Publish_Format *)0)->present),
	asn_MAP_Publish_Format_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_Publish_Format = {
	"Publish-Format",
	"Publish-Format",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_Publish_Format_constr_1, &asn_PER_type_Publish_Format_constr_1, CHOICE_constraint },
	asn_MBR_Publish_Format_1,
	2,	/* Elements count */
	&asn_SPC_Publish_Format_specs_1	/* Additional specs */
};

