/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO14827-2"
 * 	found in "../asn1c/J2735_201603DA+ITSK4-0.4_fix.update"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -pdu=MessageFrame`
 */

#ifndef	_Publication_H_
#define	_Publication_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include "Publish-Format.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Publication */
typedef struct Publication {
	BOOLEAN_t	 datexPublish_Guaranteed_bool;
	Publish_Format_t	 datexPublish_Format;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Publication_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Publication;
extern asn_SEQUENCE_specifics_t asn_SPC_Publication_specs_1;
extern asn_TYPE_member_t asn_MBR_Publication_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _Publication_H_ */
#include <asn_internal.h>
