/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO14827-2"
 * 	found in "../asn1c/J2735_201603DA+ITSK4-0.4_fix.update"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -pdu=MessageFrame`
 */

#ifndef	_Publish_Format_H_
#define	_Publish_Format_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTF8String.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Publish_Format_PR {
	Publish_Format_PR_NOTHING,	/* No components present */
	Publish_Format_PR_datexPublish_Data,
	Publish_Format_PR_datexPublish_FileName_txt
} Publish_Format_PR;

/* Forward declarations */
struct PublicationData;

/* Publish-Format */
typedef struct Publish_Format {
	Publish_Format_PR present;
	union {
		struct Publish_Format__datexPublish_Data {
			A_SEQUENCE_OF(struct PublicationData) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} datexPublish_Data;
		UTF8String_t	 datexPublish_FileName_txt;
	};
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Publish_Format_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Publish_Format;
extern asn_CHOICE_specifics_t asn_SPC_Publish_Format_specs_1;
extern asn_TYPE_member_t asn_MBR_Publish_Format_1[2];
extern asn_per_constraints_t asn_PER_type_Publish_Format_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PublicationData.h"

#endif	/* _Publish_Format_H_ */
#include <asn_internal.h>
