/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AddGrpD"
 * 	found in "../asn1c/J2735_201603DA+ITSK4-0.4_fix.update"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -pdu=MessageFrame`
 */

#include "PVD-addGrpD.h"

static int
memb_cits_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 32)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_type_cits_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..32)) */};
static asn_per_constraints_t asn_PER_type_cits_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 5,  5,  1,  32 }	/* (SIZE(1..32)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_cits_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..32)) */};
static asn_per_constraints_t asn_PER_memb_cits_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 5,  5,  1,  32 }	/* (SIZE(1..32)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_cits_2[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_CITSPVD,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_cits_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_cits_specs_2 = {
	sizeof(struct PVD_addGrpD__cits),
	offsetof(struct PVD_addGrpD__cits, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_cits_2 = {
	"cits",
	"cits",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_cits_tags_2,
	sizeof(asn_DEF_cits_tags_2)
		/sizeof(asn_DEF_cits_tags_2[0]) - 1, /* 1 */
	asn_DEF_cits_tags_2,	/* Same as above */
	sizeof(asn_DEF_cits_tags_2)
		/sizeof(asn_DEF_cits_tags_2[0]), /* 2 */
	{ &asn_OER_type_cits_constr_2, &asn_PER_type_cits_constr_2, SEQUENCE_OF_constraint },
	asn_MBR_cits_2,
	1,	/* Single element */
	&asn_SPC_cits_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_PVD_addGrpD_1[] = {
	{ ATF_POINTER, 1, offsetof(struct PVD_addGrpD, cits),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_cits_2,
		0,
		{ &asn_OER_memb_cits_constr_2, &asn_PER_memb_cits_constr_2,  memb_cits_constraint_1 },
		0, 0, /* No default value */
		"cits"
		},
};
static const int asn_MAP_PVD_addGrpD_oms_1[] = { 0 };
static const ber_tlv_tag_t asn_DEF_PVD_addGrpD_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PVD_addGrpD_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* cits */
};
asn_SEQUENCE_specifics_t asn_SPC_PVD_addGrpD_specs_1 = {
	sizeof(struct PVD_addGrpD),
	offsetof(struct PVD_addGrpD, _asn_ctx),
	asn_MAP_PVD_addGrpD_tag2el_1,
	1,	/* Count of tags in the map */
	asn_MAP_PVD_addGrpD_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_PVD_addGrpD = {
	"PVD-addGrpD",
	"PVD-addGrpD",
	&asn_OP_SEQUENCE,
	asn_DEF_PVD_addGrpD_tags_1,
	sizeof(asn_DEF_PVD_addGrpD_tags_1)
		/sizeof(asn_DEF_PVD_addGrpD_tags_1[0]), /* 1 */
	asn_DEF_PVD_addGrpD_tags_1,	/* Same as above */
	sizeof(asn_DEF_PVD_addGrpD_tags_1)
		/sizeof(asn_DEF_PVD_addGrpD_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_PVD_addGrpD_1,
	1,	/* Elements count */
	&asn_SPC_PVD_addGrpD_specs_1	/* Additional specs */
};

