/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO14827-2"
 * 	found in "../asn1c/J2735_201603DA+ITSK4-0.4_fix.update"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -pdu=MessageFrame`
 */

#include "Registered.h"

static int
memb_datexRegistered_UpdateDelay_qty_constraint_2(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 424967295)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_datexRegistered_UpdateDelay_qty_constraint_6(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 424967295)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_datexRegistered_DaysOfWeek_cd_constraint_6(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 8)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_datexRegistered_Duration_qty_constraint_6(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 65535)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_datexRegistered_UpdateDelay_qty_constr_3 CC_NOTUSED = {
	{ 4, 1 }	/* (0..424967295) */,
	-1};
static asn_per_constraints_t asn_PER_memb_datexRegistered_UpdateDelay_qty_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 29, -1,  0,  424967295 }	/* (0..424967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_datexRegistered_UpdateDelay_qty_constr_7 CC_NOTUSED = {
	{ 4, 1 }	/* (0..424967295) */,
	-1};
static asn_per_constraints_t asn_PER_memb_datexRegistered_UpdateDelay_qty_constr_7 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 29, -1,  0,  424967295 }	/* (0..424967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_datexRegistered_DaysOfWeek_cd_constr_8 CC_NOTUSED = {
	{ 0, 0 },
	8	/* (SIZE(8..8)) */};
static asn_per_constraints_t asn_PER_memb_datexRegistered_DaysOfWeek_cd_constr_8 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  8,  8 }	/* (SIZE(8..8)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_datexRegistered_Duration_qty_constr_20 CC_NOTUSED = {
	{ 2, 1 }	/* (0..65535) */,
	-1};
static asn_per_constraints_t asn_PER_memb_datexRegistered_Duration_qty_constr_20 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (0..65535) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_Registered_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_Registered_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static int asn_DFL_3_cmp_0(const void *sptr) {
	const long *st = sptr;
	
	if(!st) {
		return -1; /* No value is not a default value */
	}
	
	/* Test default value 0 */
	return (*st != 0);
}
static int asn_DFL_3_set_0(void **sptr) {
	long *st = *sptr;
	
	if(!st) {
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	/* Install default value 0 */
	*st = 0;
	return 0;
}
static asn_TYPE_member_t asn_MBR_continuous_2[] = {
	{ ATF_NOFLAGS, 3, offsetof(struct Registered__continuous, datexRegistered_UpdateDelay_qty),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_datexRegistered_UpdateDelay_qty_constr_3, &asn_PER_memb_datexRegistered_UpdateDelay_qty_constr_3,  memb_datexRegistered_UpdateDelay_qty_constraint_2 },
		&asn_DFL_3_cmp_0,	/* Compare DEFAULT 0 */
		&asn_DFL_3_set_0,	/* Set DEFAULT 0 */
		"datexRegistered-UpdateDelay-qty"
		},
	{ ATF_POINTER, 2, offsetof(struct Registered__continuous, datexRegistered_StartTime),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Time,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"datexRegistered-StartTime"
		},
	{ ATF_POINTER, 1, offsetof(struct Registered__continuous, datexRegistered_EndTime),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Time,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"datexRegistered-EndTime"
		},
};
static const int asn_MAP_continuous_oms_2[] = { 0, 1, 2 };
static const ber_tlv_tag_t asn_DEF_continuous_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_continuous_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* datexRegistered-UpdateDelay-qty */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* datexRegistered-StartTime */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* datexRegistered-EndTime */
};
static asn_SEQUENCE_specifics_t asn_SPC_continuous_specs_2 = {
	sizeof(struct Registered__continuous),
	offsetof(struct Registered__continuous, _asn_ctx),
	asn_MAP_continuous_tag2el_2,
	3,	/* Count of tags in the map */
	asn_MAP_continuous_oms_2,	/* Optional members */
	3, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_continuous_2 = {
	"continuous",
	"continuous",
	&asn_OP_SEQUENCE,
	asn_DEF_continuous_tags_2,
	sizeof(asn_DEF_continuous_tags_2)
		/sizeof(asn_DEF_continuous_tags_2[0]) - 1, /* 1 */
	asn_DEF_continuous_tags_2,	/* Same as above */
	sizeof(asn_DEF_continuous_tags_2)
		/sizeof(asn_DEF_continuous_tags_2[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_continuous_2,
	3,	/* Elements count */
	&asn_SPC_continuous_specs_2	/* Additional specs */
};

static int asn_DFL_7_cmp_0(const void *sptr) {
	const long *st = sptr;
	
	if(!st) {
		return -1; /* No value is not a default value */
	}
	
	/* Test default value 0 */
	return (*st != 0);
}
static int asn_DFL_7_set_0(void **sptr) {
	long *st = *sptr;
	
	if(!st) {
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	/* Install default value 0 */
	*st = 0;
	return 0;
}
static asn_TYPE_member_t asn_MBR_daily_6[] = {
	{ ATF_NOFLAGS, 1, offsetof(struct Registered__daily, datexRegistered_UpdateDelay_qty),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_datexRegistered_UpdateDelay_qty_constr_7, &asn_PER_memb_datexRegistered_UpdateDelay_qty_constr_7,  memb_datexRegistered_UpdateDelay_qty_constraint_6 },
		&asn_DFL_7_cmp_0,	/* Compare DEFAULT 0 */
		&asn_DFL_7_set_0,	/* Set DEFAULT 0 */
		"datexRegistered-UpdateDelay-qty"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Registered__daily, datexRegistered_DaysOfWeek_cd),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,
		{ &asn_OER_memb_datexRegistered_DaysOfWeek_cd_constr_8, &asn_PER_memb_datexRegistered_DaysOfWeek_cd_constr_8,  memb_datexRegistered_DaysOfWeek_cd_constraint_6 },
		0, 0, /* No default value */
		"datexRegistered-DaysOfWeek-cd"
		},
	{ ATF_POINTER, 4, offsetof(struct Registered__daily, datexRegistered_StartDate),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Time,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"datexRegistered-StartDate"
		},
	{ ATF_POINTER, 3, offsetof(struct Registered__daily, datexRegistered_EndDate),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Time,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"datexRegistered-EndDate"
		},
	{ ATF_POINTER, 2, offsetof(struct Registered__daily, datexRegistered_StartTime),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Time,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"datexRegistered-StartTime"
		},
	{ ATF_POINTER, 1, offsetof(struct Registered__daily, datexRegistered_Duration_qty),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_datexRegistered_Duration_qty_constr_20, &asn_PER_memb_datexRegistered_Duration_qty_constr_20,  memb_datexRegistered_Duration_qty_constraint_6 },
		0, 0, /* No default value */
		"datexRegistered-Duration-qty"
		},
};
static const int asn_MAP_daily_oms_6[] = { 0, 2, 3, 4, 5 };
static const ber_tlv_tag_t asn_DEF_daily_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_daily_tag2el_6[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* datexRegistered-UpdateDelay-qty */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* datexRegistered-DaysOfWeek-cd */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* datexRegistered-StartDate */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* datexRegistered-EndDate */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* datexRegistered-StartTime */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* datexRegistered-Duration-qty */
};
static asn_SEQUENCE_specifics_t asn_SPC_daily_specs_6 = {
	sizeof(struct Registered__daily),
	offsetof(struct Registered__daily, _asn_ctx),
	asn_MAP_daily_tag2el_6,
	6,	/* Count of tags in the map */
	asn_MAP_daily_oms_6,	/* Optional members */
	5, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_daily_6 = {
	"daily",
	"daily",
	&asn_OP_SEQUENCE,
	asn_DEF_daily_tags_6,
	sizeof(asn_DEF_daily_tags_6)
		/sizeof(asn_DEF_daily_tags_6[0]) - 1, /* 1 */
	asn_DEF_daily_tags_6,	/* Same as above */
	sizeof(asn_DEF_daily_tags_6)
		/sizeof(asn_DEF_daily_tags_6[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_daily_6,
	6,	/* Elements count */
	&asn_SPC_daily_specs_6	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_Registered_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Registered, continuous),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_continuous_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"continuous"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Registered, daily),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_daily_6,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"daily"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_Registered_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* continuous */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* daily */
};
asn_CHOICE_specifics_t asn_SPC_Registered_specs_1 = {
	sizeof(struct Registered),
	offsetof(struct Registered, _asn_ctx),
	offsetof(struct Registered, present),
	sizeof(((struct Registered *)0)->present),
	asn_MAP_Registered_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_Registered = {
	"Registered",
	"Registered",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_Registered_constr_1, &asn_PER_type_Registered_constr_1, CHOICE_constraint },
	asn_MBR_Registered_1,
	2,	/* Elements count */
	&asn_SPC_Registered_specs_1	/* Additional specs */
};

