/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../asn1c/J2735_201603DA+ITSK4-0.4_fix.update"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -pdu=MessageFrame`
 */

#ifndef	_RegionalExtensionProbeVehicleData_H_
#define	_RegionalExtensionProbeVehicleData_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RegionId.h"
#include <ANY.h>
#include <asn_ioc.h>
#include "PVD-addGrpD.h"
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RegionalExtensionProbeVehicleData__regExtValue_PR {
	RegionalExtensionProbeVehicleData__regExtValue_PR_NOTHING,	/* No components present */
	RegionalExtensionProbeVehicleData__regExtValue_PR_PVD_addGrpD
} RegionalExtensionProbeVehicleData__regExtValue_PR;

/* RegionalExtensionProbeVehicleData */
typedef struct RegionalExtensionProbeVehicleData {
	RegionId_t	 regionId;
	struct RegionalExtensionProbeVehicleData__regExtValue {
		RegionalExtensionProbeVehicleData__regExtValue_PR present;
		union {
			PVD_addGrpD_t	 PVD_addGrpD;
		};
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtensionProbeVehicleData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtensionProbeVehicleData;
extern asn_SEQUENCE_specifics_t asn_SPC_RegionalExtensionProbeVehicleData_specs_1;
extern asn_TYPE_member_t asn_MBR_RegionalExtensionProbeVehicleData_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _RegionalExtensionProbeVehicleData_H_ */
#include <asn_internal.h>
