/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO14827-2"
 * 	found in "../asn1c/J2735_201603DA+ITSK4-0.4_fix.update"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -pdu=MessageFrame`
 */

#include "RejectType.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_datexReject_Login_cd_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_datexReject_Login_cd_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  4,  4,  0,  9 }	/* (0..9,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_datexReject_Subscription_cd_constr_14 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_datexReject_Subscription_cd_constr_14 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  4,  4,  0,  9 }	/* (0..9,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_datexReject_Publication_cd_constr_26 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_datexReject_Publication_cd_constr_26 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  3,  3,  0,  7 }	/* (0..7,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_RejectType_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_RejectType_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_datexReject_Login_cd_value2enum_2[] = {
	{ 0,	5,	"other" },
	{ 1,	17,	"unknownDomainName" },
	{ 2,	12,	"accessDenied" },
	{ 3,	19,	"invalidNamePassword" },
	{ 4,	15,	"timeoutTooSmall" },
	{ 5,	15,	"timeoutTooLarge" },
	{ 6,	17,	"heartbeatTooSmall" },
	{ 7,	17,	"heartbeatTooLarge" },
	{ 8,	13,	"sessionExists" },
	{ 9,	18,	"maxSessionsReached" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_datexReject_Login_cd_enum2value_2[] = {
	2,	/* accessDenied(2) */
	7,	/* heartbeatTooLarge(7) */
	6,	/* heartbeatTooSmall(6) */
	3,	/* invalidNamePassword(3) */
	9,	/* maxSessionsReached(9) */
	0,	/* other(0) */
	8,	/* sessionExists(8) */
	5,	/* timeoutTooLarge(5) */
	4,	/* timeoutTooSmall(4) */
	1	/* unknownDomainName(1) */
	/* This list is extensible */
};
static const asn_INTEGER_specifics_t asn_SPC_datexReject_Login_cd_specs_2 = {
	asn_MAP_datexReject_Login_cd_value2enum_2,	/* "tag" => N; sorted by tag */
	asn_MAP_datexReject_Login_cd_enum2value_2,	/* N => "tag"; sorted by N */
	10,	/* Number of elements in the maps */
	11,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_datexReject_Login_cd_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_datexReject_Login_cd_2 = {
	"datexReject-Login-cd",
	"datexReject-Login-cd",
	&asn_OP_NativeEnumerated,
	asn_DEF_datexReject_Login_cd_tags_2,
	sizeof(asn_DEF_datexReject_Login_cd_tags_2)
		/sizeof(asn_DEF_datexReject_Login_cd_tags_2[0]) - 1, /* 1 */
	asn_DEF_datexReject_Login_cd_tags_2,	/* Same as above */
	sizeof(asn_DEF_datexReject_Login_cd_tags_2)
		/sizeof(asn_DEF_datexReject_Login_cd_tags_2[0]), /* 2 */
	{ &asn_OER_type_datexReject_Login_cd_constr_2, &asn_PER_type_datexReject_Login_cd_constr_2, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_datexReject_Login_cd_specs_2	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_datexReject_Subscription_cd_value2enum_14[] = {
	{ 0,	5,	"other" },
	{ 1,	22,	"unknownSubscriptionNbr" },
	{ 2,	12,	"invalidTimes" },
	{ 3,	17,	"frequencyTooSmall" },
	{ 4,	17,	"frequencyTooLarge" },
	{ 5,	12,	"invalid-mode" },
	{ 6,	25,	"publishFormatNotSupported" },
	{ 7,	23,	"unknowSubscriptionMsgId" },
	{ 8,	24,	"invalidSubscriptionMsgId" },
	{ 9,	26,	"invalidSubscriptionContent" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_datexReject_Subscription_cd_enum2value_14[] = {
	4,	/* frequencyTooLarge(4) */
	3,	/* frequencyTooSmall(3) */
	5,	/* invalid-mode(5) */
	9,	/* invalidSubscriptionContent(9) */
	8,	/* invalidSubscriptionMsgId(8) */
	2,	/* invalidTimes(2) */
	0,	/* other(0) */
	6,	/* publishFormatNotSupported(6) */
	7,	/* unknowSubscriptionMsgId(7) */
	1	/* unknownSubscriptionNbr(1) */
	/* This list is extensible */
};
static const asn_INTEGER_specifics_t asn_SPC_datexReject_Subscription_cd_specs_14 = {
	asn_MAP_datexReject_Subscription_cd_value2enum_14,	/* "tag" => N; sorted by tag */
	asn_MAP_datexReject_Subscription_cd_enum2value_14,	/* N => "tag"; sorted by N */
	10,	/* Number of elements in the maps */
	11,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_datexReject_Subscription_cd_tags_14[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_datexReject_Subscription_cd_14 = {
	"datexReject-Subscription-cd",
	"datexReject-Subscription-cd",
	&asn_OP_NativeEnumerated,
	asn_DEF_datexReject_Subscription_cd_tags_14,
	sizeof(asn_DEF_datexReject_Subscription_cd_tags_14)
		/sizeof(asn_DEF_datexReject_Subscription_cd_tags_14[0]) - 1, /* 1 */
	asn_DEF_datexReject_Subscription_cd_tags_14,	/* Same as above */
	sizeof(asn_DEF_datexReject_Subscription_cd_tags_14)
		/sizeof(asn_DEF_datexReject_Subscription_cd_tags_14[0]), /* 2 */
	{ &asn_OER_type_datexReject_Subscription_cd_constr_14, &asn_PER_type_datexReject_Subscription_cd_constr_14, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_datexReject_Subscription_cd_specs_14	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_datexReject_Publication_cd_value2enum_26[] = {
	{ 0,	5,	"other" },
	{ 1,	19,	"unknownSubscription" },
	{ 2,	21,	"unknownPublicationNbr" },
	{ 3,	20,	"invalidPublishFormat" },
	{ 4,	23,	"unknownPublicationMsgId" },
	{ 5,	23,	"invalidPublicationMsgId" },
	{ 6,	28,	"invalidPublicationMsgContent" },
	{ 7,	22,	"repeatedPublicationNbr" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_datexReject_Publication_cd_enum2value_26[] = {
	6,	/* invalidPublicationMsgContent(6) */
	5,	/* invalidPublicationMsgId(5) */
	3,	/* invalidPublishFormat(3) */
	0,	/* other(0) */
	7,	/* repeatedPublicationNbr(7) */
	4,	/* unknownPublicationMsgId(4) */
	2,	/* unknownPublicationNbr(2) */
	1	/* unknownSubscription(1) */
	/* This list is extensible */
};
static const asn_INTEGER_specifics_t asn_SPC_datexReject_Publication_cd_specs_26 = {
	asn_MAP_datexReject_Publication_cd_value2enum_26,	/* "tag" => N; sorted by tag */
	asn_MAP_datexReject_Publication_cd_enum2value_26,	/* N => "tag"; sorted by N */
	8,	/* Number of elements in the maps */
	9,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_datexReject_Publication_cd_tags_26[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_datexReject_Publication_cd_26 = {
	"datexReject-Publication-cd",
	"datexReject-Publication-cd",
	&asn_OP_NativeEnumerated,
	asn_DEF_datexReject_Publication_cd_tags_26,
	sizeof(asn_DEF_datexReject_Publication_cd_tags_26)
		/sizeof(asn_DEF_datexReject_Publication_cd_tags_26[0]) - 1, /* 1 */
	asn_DEF_datexReject_Publication_cd_tags_26,	/* Same as above */
	sizeof(asn_DEF_datexReject_Publication_cd_tags_26)
		/sizeof(asn_DEF_datexReject_Publication_cd_tags_26[0]), /* 2 */
	{ &asn_OER_type_datexReject_Publication_cd_constr_26, &asn_PER_type_datexReject_Publication_cd_constr_26, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_datexReject_Publication_cd_specs_26	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_RejectType_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RejectType, datexReject_Login_cd),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_datexReject_Login_cd_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"datexReject-Login-cd"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RejectType, datexReject_Subscription_cd),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_datexReject_Subscription_cd_14,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"datexReject-Subscription-cd"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RejectType, datexReject_Publication_cd),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_datexReject_Publication_cd_26,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"datexReject-Publication-cd"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_RejectType_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* datexReject-Login-cd */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* datexReject-Subscription-cd */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* datexReject-Publication-cd */
};
asn_CHOICE_specifics_t asn_SPC_RejectType_specs_1 = {
	sizeof(struct RejectType),
	offsetof(struct RejectType, _asn_ctx),
	offsetof(struct RejectType, present),
	sizeof(((struct RejectType *)0)->present),
	asn_MAP_RejectType_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_RejectType = {
	"RejectType",
	"RejectType",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_RejectType_constr_1, &asn_PER_type_RejectType_constr_1, CHOICE_constraint },
	asn_MBR_RejectType_1,
	3,	/* Elements count */
	&asn_SPC_RejectType_specs_1	/* Additional specs */
};

