/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO14827-2"
 * 	found in "../asn1c/J2735_201603DA+ITSK4-0.4_fix.update"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -pdu=MessageFrame`
 */

#include "Reject.h"

static int
datexReject_Packet_nbr_2_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

/*
 * This type is implemented using NativeInteger,
 * so here we adjust the DEF accordingly.
 */
static int
memb_datexReject_Packet_nbr_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

static asn_oer_constraints_t asn_OER_type_datexReject_Packet_nbr_constr_2 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_type_datexReject_Packet_nbr_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_datexReject_Packet_nbr_constr_2 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_memb_datexReject_Packet_nbr_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_specifics_t asn_SPC_datexReject_Packet_nbr_specs_2 = {
	0,	0,	0,	0,	0,
	0,	/* Native long size */
	1	/* Unsigned representation */
};
static const ber_tlv_tag_t asn_DEF_datexReject_Packet_nbr_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_datexReject_Packet_nbr_2 = {
	"datexReject-Packet-nbr",
	"datexReject-Packet-nbr",
	&asn_OP_NativeInteger,
	asn_DEF_datexReject_Packet_nbr_tags_2,
	sizeof(asn_DEF_datexReject_Packet_nbr_tags_2)
		/sizeof(asn_DEF_datexReject_Packet_nbr_tags_2[0]) - 1, /* 1 */
	asn_DEF_datexReject_Packet_nbr_tags_2,	/* Same as above */
	sizeof(asn_DEF_datexReject_Packet_nbr_tags_2)
		/sizeof(asn_DEF_datexReject_Packet_nbr_tags_2[0]), /* 2 */
	{ &asn_OER_type_datexReject_Packet_nbr_constr_2, &asn_PER_type_datexReject_Packet_nbr_constr_2, datexReject_Packet_nbr_2_constraint },
	0, 0,	/* No members */
	&asn_SPC_datexReject_Packet_nbr_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_Reject_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Reject, datexReject_Packet_nbr),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_datexReject_Packet_nbr_2,
		0,
		{ &asn_OER_memb_datexReject_Packet_nbr_constr_2, &asn_PER_memb_datexReject_Packet_nbr_constr_2,  memb_datexReject_Packet_nbr_constraint_1 },
		0, 0, /* No default value */
		"datexReject-Packet-nbr"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Reject, datexReject_Type),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_RejectType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"datexReject-Type"
		},
	{ ATF_POINTER, 1, offsetof(struct Reject, datexReject_AlternateRequest),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_AlternateRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"datexReject-AlternateRequest"
		},
};
static const int asn_MAP_Reject_oms_1[] = { 2 };
static const ber_tlv_tag_t asn_DEF_Reject_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Reject_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* datexReject-Packet-nbr */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* datexReject-Type */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* datexReject-AlternateRequest */
};
asn_SEQUENCE_specifics_t asn_SPC_Reject_specs_1 = {
	sizeof(struct Reject),
	offsetof(struct Reject, _asn_ctx),
	asn_MAP_Reject_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_Reject_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Reject = {
	"Reject",
	"Reject",
	&asn_OP_SEQUENCE,
	asn_DEF_Reject_tags_1,
	sizeof(asn_DEF_Reject_tags_1)
		/sizeof(asn_DEF_Reject_tags_1[0]), /* 1 */
	asn_DEF_Reject_tags_1,	/* Same as above */
	sizeof(asn_DEF_Reject_tags_1)
		/sizeof(asn_DEF_Reject_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Reject_1,
	3,	/* Elements count */
	&asn_SPC_Reject_specs_1	/* Additional specs */
};

