/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO14827-2"
 * 	found in "../asn1c/J2735_201603DA+ITSK4-0.4_fix.update"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -pdu=MessageFrame`
 */

#ifndef	_Reject_H_
#define	_Reject_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "RejectType.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AlternateRequest;

/* Reject */
typedef struct Reject {
	unsigned long	 datexReject_Packet_nbr;
	RejectType_t	 datexReject_Type;
	struct AlternateRequest	*datexReject_AlternateRequest	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Reject_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_datexReject_Packet_nbr_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_Reject;
extern asn_SEQUENCE_specifics_t asn_SPC_Reject_specs_1;
extern asn_TYPE_member_t asn_MBR_Reject_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AlternateRequest.h"

#endif	/* _Reject_H_ */
#include <asn_internal.h>
