/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AddGrpD"
 * 	found in "../asn1c/J2735_201603DA+ITSK4-0.4_fix.update"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -pdu=MessageFrame`
 */

#ifndef	_RSA_addGrpD_H_
#define	_RSA_addGrpD_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CITSRSA;

/* RSA-addGrpD */
typedef struct RSA_addGrpD {
	struct CITSRSA	*cits	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RSA_addGrpD_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RSA_addGrpD;
extern asn_SEQUENCE_specifics_t asn_SPC_RSA_addGrpD_specs_1;
extern asn_TYPE_member_t asn_MBR_RSA_addGrpD_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CITSRSA.h"

#endif	/* _RSA_addGrpD_H_ */
#include <asn_internal.h>
