/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO14827-2"
 * 	found in "../asn1c/J2735_201603DA+ITSK4-0.4_fix.update"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -pdu=MessageFrame`
 */

#ifndef	_SubscriptionType_H_
#define	_SubscriptionType_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SubscriptionData.h"
#include <NativeEnumerated.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SubscriptionType_PR {
	SubscriptionType_PR_NOTHING,	/* No components present */
	SubscriptionType_PR_subscription,
	SubscriptionType_PR_datexSubscribe_CancelReason_cd
} SubscriptionType_PR;
typedef enum SubscriptionType__datexSubscribe_CancelReason_cd {
	SubscriptionType__datexSubscribe_CancelReason_cd_other	= 0,
	SubscriptionType__datexSubscribe_CancelReason_cd_dataNotNeeded	= 1,
	SubscriptionType__datexSubscribe_CancelReason_cd_errorsInPublication	= 2,
	SubscriptionType__datexSubscribe_CancelReason_cd_pendingLogout	= 3,
	SubscriptionType__datexSubscribe_CancelReason_cd_processingMgmt	= 4,
	SubscriptionType__datexSubscribe_CancelReason_cd_bandwidthMgmt	= 5
	/*
	 * Enumeration is extensible
	 */
} e_SubscriptionType__datexSubscribe_CancelReason_cd;

/* SubscriptionType */
typedef struct SubscriptionType {
	SubscriptionType_PR present;
	union {
		SubscriptionData_t	 subscription;
		long	 datexSubscribe_CancelReason_cd;
	};
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SubscriptionType_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_datexSubscribe_CancelReason_cd_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_SubscriptionType;
extern asn_CHOICE_specifics_t asn_SPC_SubscriptionType_specs_1;
extern asn_TYPE_member_t asn_MBR_SubscriptionType_1[2];
extern asn_per_constraints_t asn_PER_type_SubscriptionType_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _SubscriptionType_H_ */
#include <asn_internal.h>
