/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO14827-2"
 * 	found in "../asn1c/J2735_201603DA+ITSK4-0.4_fix.update"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -pdu=MessageFrame`
 */

#include "SubscriptionMode.h"

static asn_oer_constraints_t asn_OER_type_SubscriptionMode_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_SubscriptionMode_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_SubscriptionMode_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SubscriptionMode, single),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"single"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SubscriptionMode, event_driven),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Registered,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"event-driven"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SubscriptionMode, periodic),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Registered,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"periodic"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_SubscriptionMode_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* single */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* event-driven */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* periodic */
};
asn_CHOICE_specifics_t asn_SPC_SubscriptionMode_specs_1 = {
	sizeof(struct SubscriptionMode),
	offsetof(struct SubscriptionMode, _asn_ctx),
	offsetof(struct SubscriptionMode, present),
	sizeof(((struct SubscriptionMode *)0)->present),
	asn_MAP_SubscriptionMode_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_SubscriptionMode = {
	"SubscriptionMode",
	"SubscriptionMode",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_SubscriptionMode_constr_1, &asn_PER_type_SubscriptionMode_constr_1, CHOICE_constraint },
	asn_MBR_SubscriptionMode_1,
	3,	/* Elements count */
	&asn_SPC_SubscriptionMode_specs_1	/* Additional specs */
};

