/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO14827-2"
 * 	found in "../asn1c/J2735_201603DA+ITSK4-0.4_fix.update"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -pdu=MessageFrame`
 */

#include "SubscriptionType.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_datexSubscribe_CancelReason_cd_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_datexSubscribe_CancelReason_cd_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  3,  3,  0,  5 }	/* (0..5,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_SubscriptionType_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_SubscriptionType_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_datexSubscribe_CancelReason_cd_value2enum_3[] = {
	{ 0,	5,	"other" },
	{ 1,	13,	"dataNotNeeded" },
	{ 2,	19,	"errorsInPublication" },
	{ 3,	13,	"pendingLogout" },
	{ 4,	14,	"processingMgmt" },
	{ 5,	13,	"bandwidthMgmt" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_datexSubscribe_CancelReason_cd_enum2value_3[] = {
	5,	/* bandwidthMgmt(5) */
	1,	/* dataNotNeeded(1) */
	2,	/* errorsInPublication(2) */
	0,	/* other(0) */
	3,	/* pendingLogout(3) */
	4	/* processingMgmt(4) */
	/* This list is extensible */
};
static const asn_INTEGER_specifics_t asn_SPC_datexSubscribe_CancelReason_cd_specs_3 = {
	asn_MAP_datexSubscribe_CancelReason_cd_value2enum_3,	/* "tag" => N; sorted by tag */
	asn_MAP_datexSubscribe_CancelReason_cd_enum2value_3,	/* N => "tag"; sorted by N */
	6,	/* Number of elements in the maps */
	7,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_datexSubscribe_CancelReason_cd_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_datexSubscribe_CancelReason_cd_3 = {
	"datexSubscribe-CancelReason-cd",
	"datexSubscribe-CancelReason-cd",
	&asn_OP_NativeEnumerated,
	asn_DEF_datexSubscribe_CancelReason_cd_tags_3,
	sizeof(asn_DEF_datexSubscribe_CancelReason_cd_tags_3)
		/sizeof(asn_DEF_datexSubscribe_CancelReason_cd_tags_3[0]) - 1, /* 1 */
	asn_DEF_datexSubscribe_CancelReason_cd_tags_3,	/* Same as above */
	sizeof(asn_DEF_datexSubscribe_CancelReason_cd_tags_3)
		/sizeof(asn_DEF_datexSubscribe_CancelReason_cd_tags_3[0]), /* 2 */
	{ &asn_OER_type_datexSubscribe_CancelReason_cd_constr_3, &asn_PER_type_datexSubscribe_CancelReason_cd_constr_3, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_datexSubscribe_CancelReason_cd_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_SubscriptionType_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SubscriptionType, subscription),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SubscriptionData,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"subscription"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SubscriptionType, datexSubscribe_CancelReason_cd),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_datexSubscribe_CancelReason_cd_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"datexSubscribe-CancelReason-cd"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_SubscriptionType_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* subscription */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* datexSubscribe-CancelReason-cd */
};
asn_CHOICE_specifics_t asn_SPC_SubscriptionType_specs_1 = {
	sizeof(struct SubscriptionType),
	offsetof(struct SubscriptionType, _asn_ctx),
	offsetof(struct SubscriptionType, present),
	sizeof(((struct SubscriptionType *)0)->present),
	asn_MAP_SubscriptionType_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_SubscriptionType = {
	"SubscriptionType",
	"SubscriptionType",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_SubscriptionType_constr_1, &asn_PER_type_SubscriptionType_constr_1, CHOICE_constraint },
	asn_MBR_SubscriptionType_1,
	2,	/* Elements count */
	&asn_SPC_SubscriptionType_specs_1	/* Additional specs */
};

