/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO14827-2"
 * 	found in "../asn1c/J2735_201603DA+ITSK4-0.4_fix.update"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -pdu=MessageFrame`
 */

#include "SubscriptionData.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static int
memb_datexSubscription_Priority_nbr_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1 && value <= 10)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_type_datexSubscribe_Status_cd_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_datexSubscribe_Status_cd_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_datexSubscribe_PublishFormat_cd_constr_7 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_datexSubscribe_PublishFormat_cd_constr_7 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  2,  2,  0,  3 }	/* (0..3,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_datexSubscription_Priority_nbr_constr_13 CC_NOTUSED = {
	{ 1, 1 }	/* (1..10) */,
	-1};
static asn_per_constraints_t asn_PER_memb_datexSubscription_Priority_nbr_constr_13 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  1,  10 }	/* (1..10) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_datexSubscribe_Status_cd_value2enum_3[] = {
	{ 0,	3,	"new" },
	{ 1,	6,	"update" }
};
static const unsigned int asn_MAP_datexSubscribe_Status_cd_enum2value_3[] = {
	0,	/* new(0) */
	1	/* update(1) */
};
static const asn_INTEGER_specifics_t asn_SPC_datexSubscribe_Status_cd_specs_3 = {
	asn_MAP_datexSubscribe_Status_cd_value2enum_3,	/* "tag" => N; sorted by tag */
	asn_MAP_datexSubscribe_Status_cd_enum2value_3,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_datexSubscribe_Status_cd_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_datexSubscribe_Status_cd_3 = {
	"datexSubscribe-Status-cd",
	"datexSubscribe-Status-cd",
	&asn_OP_NativeEnumerated,
	asn_DEF_datexSubscribe_Status_cd_tags_3,
	sizeof(asn_DEF_datexSubscribe_Status_cd_tags_3)
		/sizeof(asn_DEF_datexSubscribe_Status_cd_tags_3[0]) - 1, /* 1 */
	asn_DEF_datexSubscribe_Status_cd_tags_3,	/* Same as above */
	sizeof(asn_DEF_datexSubscribe_Status_cd_tags_3)
		/sizeof(asn_DEF_datexSubscribe_Status_cd_tags_3[0]), /* 2 */
	{ &asn_OER_type_datexSubscribe_Status_cd_constr_3, &asn_PER_type_datexSubscribe_Status_cd_constr_3, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_datexSubscribe_Status_cd_specs_3	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_datexSubscribe_PublishFormat_cd_value2enum_7[] = {
	{ 0,	5,	"other" },
	{ 1,	3,	"ftp" },
	{ 2,	4,	"tftp" },
	{ 3,	10,	"dataPacket" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_datexSubscribe_PublishFormat_cd_enum2value_7[] = {
	3,	/* dataPacket(3) */
	1,	/* ftp(1) */
	0,	/* other(0) */
	2	/* tftp(2) */
	/* This list is extensible */
};
static const asn_INTEGER_specifics_t asn_SPC_datexSubscribe_PublishFormat_cd_specs_7 = {
	asn_MAP_datexSubscribe_PublishFormat_cd_value2enum_7,	/* "tag" => N; sorted by tag */
	asn_MAP_datexSubscribe_PublishFormat_cd_enum2value_7,	/* N => "tag"; sorted by N */
	4,	/* Number of elements in the maps */
	5,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_datexSubscribe_PublishFormat_cd_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_datexSubscribe_PublishFormat_cd_7 = {
	"datexSubscribe-PublishFormat-cd",
	"datexSubscribe-PublishFormat-cd",
	&asn_OP_NativeEnumerated,
	asn_DEF_datexSubscribe_PublishFormat_cd_tags_7,
	sizeof(asn_DEF_datexSubscribe_PublishFormat_cd_tags_7)
		/sizeof(asn_DEF_datexSubscribe_PublishFormat_cd_tags_7[0]) - 1, /* 1 */
	asn_DEF_datexSubscribe_PublishFormat_cd_tags_7,	/* Same as above */
	sizeof(asn_DEF_datexSubscribe_PublishFormat_cd_tags_7)
		/sizeof(asn_DEF_datexSubscribe_PublishFormat_cd_tags_7[0]), /* 2 */
	{ &asn_OER_type_datexSubscribe_PublishFormat_cd_constr_7, &asn_PER_type_datexSubscribe_PublishFormat_cd_constr_7, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_datexSubscribe_PublishFormat_cd_specs_7	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_SubscriptionData_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SubscriptionData, datexSubscribe_Persistent_bool),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"datexSubscribe-Persistent-bool"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SubscriptionData, datexSubscribe_Status_cd),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_datexSubscribe_Status_cd_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"datexSubscribe-Status-cd"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SubscriptionData, datexSubscribe_Mode),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_SubscriptionMode,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"datexSubscribe-Mode"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SubscriptionData, datexSubscribe_PublishFormat_cd),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_datexSubscribe_PublishFormat_cd_7,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"datexSubscribe-PublishFormat-cd"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SubscriptionData, datexSubscription_Priority_nbr),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_datexSubscription_Priority_nbr_constr_13, &asn_PER_memb_datexSubscription_Priority_nbr_constr_13,  memb_datexSubscription_Priority_nbr_constraint_1 },
		0, 0, /* No default value */
		"datexSubscription-Priority-nbr"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SubscriptionData, datexSubscribe_Guarantee_bool),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"datexSubscribe-Guarantee-bool"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SubscriptionData, datexSubscribe_Pdu),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MessageFrame,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"datexSubscribe-Pdu"
		},
};
static const ber_tlv_tag_t asn_DEF_SubscriptionData_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SubscriptionData_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* datexSubscribe-Persistent-bool */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* datexSubscribe-Status-cd */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* datexSubscribe-Mode */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* datexSubscribe-PublishFormat-cd */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* datexSubscription-Priority-nbr */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* datexSubscribe-Guarantee-bool */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 } /* datexSubscribe-Pdu */
};
asn_SEQUENCE_specifics_t asn_SPC_SubscriptionData_specs_1 = {
	sizeof(struct SubscriptionData),
	offsetof(struct SubscriptionData, _asn_ctx),
	asn_MAP_SubscriptionData_tag2el_1,
	7,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SubscriptionData = {
	"SubscriptionData",
	"SubscriptionData",
	&asn_OP_SEQUENCE,
	asn_DEF_SubscriptionData_tags_1,
	sizeof(asn_DEF_SubscriptionData_tags_1)
		/sizeof(asn_DEF_SubscriptionData_tags_1[0]), /* 1 */
	asn_DEF_SubscriptionData_tags_1,	/* Same as above */
	sizeof(asn_DEF_SubscriptionData_tags_1)
		/sizeof(asn_DEF_SubscriptionData_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SubscriptionData_1,
	7,	/* Elements count */
	&asn_SPC_SubscriptionData_specs_1	/* Additional specs */
};

