/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO14827-2"
 * 	found in "../asn1c/J2735_201603DA+ITSK4-0.4_fix.update"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -pdu=MessageFrame`
 */

#ifndef	_SubscriptionMode_H_
#define	_SubscriptionMode_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include "Registered.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SubscriptionMode_PR {
	SubscriptionMode_PR_NOTHING,	/* No components present */
	SubscriptionMode_PR_single,
	SubscriptionMode_PR_event_driven,
	SubscriptionMode_PR_periodic
} SubscriptionMode_PR;

/* SubscriptionMode */
typedef struct SubscriptionMode {
	SubscriptionMode_PR present;
	union {
		NULL_t	 single;
		Registered_t	 event_driven;
		Registered_t	 periodic;
	};
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SubscriptionMode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SubscriptionMode;
extern asn_CHOICE_specifics_t asn_SPC_SubscriptionMode_specs_1;
extern asn_TYPE_member_t asn_MBR_SubscriptionMode_1[3];
extern asn_per_constraints_t asn_PER_type_SubscriptionMode_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _SubscriptionMode_H_ */
#include <asn_internal.h>
