/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO14827-2"
 * 	found in "../asn1c/J2735_201603DA+ITSK4-0.4_fix.update"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -pdu=MessageFrame`
 */

#ifndef	_Terminate_H_
#define	_Terminate_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Terminate {
	Terminate_other	= 0,
	Terminate_serverRequested	= 1,
	Terminate_clientRequested	= 2,
	Terminate_serverShutdown	= 3,
	Terminate_clientShutdown	= 4,
	Terminate_serverCommProblems	= 5,
	Terminate_clientCommProblems	= 6
	/*
	 * Enumeration is extensible
	 */
} e_Terminate;

/* Terminate */
typedef long	 Terminate_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Terminate_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Terminate;
extern const asn_INTEGER_specifics_t asn_SPC_Terminate_specs_1;
asn_struct_free_f Terminate_free;
asn_struct_print_f Terminate_print;
asn_constr_check_f Terminate_constraint;
ber_type_decoder_f Terminate_decode_ber;
der_type_encoder_f Terminate_encode_der;
xer_type_decoder_f Terminate_decode_xer;
xer_type_encoder_f Terminate_encode_xer;
oer_type_decoder_f Terminate_decode_oer;
oer_type_encoder_f Terminate_encode_oer;
per_type_decoder_f Terminate_decode_uper;
per_type_encoder_f Terminate_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Terminate_H_ */
#include <asn_internal.h>
