/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO14827-2"
 * 	found in "../asn1c/J2735_201603DA+ITSK4-0.4_fix.update"
 * 	`asn1c -no-gen-example -fcompound-names -funnamed-unions -pdu=MessageFrame`
 */

#ifndef	_TransferDone_H_
#define	_TransferDone_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <UTF8String.h>
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TransferDone */
typedef struct TransferDone {
	unsigned long	 datexTransferDone_Publication_nbr;
	UTF8String_t	 datexTransferDone_FileName_txt;
	BOOLEAN_t	 datexTransferDone_Success_bool;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TransferDone_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_datexTransferDone_Publication_nbr_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_TransferDone;
extern asn_SEQUENCE_specifics_t asn_SPC_TransferDone_specs_1;
extern asn_TYPE_member_t asn_MBR_TransferDone_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _TransferDone_H_ */
#include <asn_internal.h>
